### ISSUE TITLE
feat: create issues in new feature

### ISSUE THREAD

**Issue by ddthien-coder** [deveyy/node-backend#12]
Please send email: thiendinh.dev@gmail.com

**Comment by ddthien-coder** [comment]
https://github.com/deveyy/bdigital-backend/commit/fd62f05450fa199b46e1fde81cea65787aaf82f4

**Comment by deveyy** [comment]
https://github.com/deveyy/bdigital-backend/commit/fd62f05450fa199b46e1fde81cea65787aaf82f4
