### ISSUE TITLE
issue: Joi schema validation decorator not cascading error found to error middleware

### ISSUE THREAD

**Issue by ddthien-coder** [deveyy/node-backend#21]
The joi validator decorator isn't sending the error to the general error middleware. it just throws the error and crashes the server if there is an error in the request object. I think it would be better to use

return next(new JoiRequestValidationError(error.details[0].message))

instead of

throw new JoiRequestValidationError(error.details[0].message)

this way , when we call the next function, the middleware is explicitly told to take the error and respond to it. This fixed my issue.

![image](https://user-images.githubusercontent.com/55986641/193500483-a78425d7-e181-47c8-a336-e3a20c90799c.png)

**Comment by deveyy** [comment]
> The joi validator decorator isn't sending the error to the general error middleware. it just throws the error and crashes the server if there is an error in the request object. I think it would be better to use
> 
> return next(new JoiRequestValidationError(error.details[0].message))
> 
> instead of
> 
> throw new JoiRequestValidationError(error.details[0].message)
> 
> this way , when we call the next function, the middleware is explicitly told to take the error and respond to it. This fixed my issue.
> 
> ![image](https://user-images.githubusercontent.com/55986641/193500483-a78425d7-e181-47c8-a336-e3a20c90799c.png)

i'm checked
